// packages/svelte/src/SplitFlap.svelte
<script lang="ts">
  import { SplitFlap as SplitFlapCore } from "@splitflap/core";
  import type { SplitFlapOptions } from "@splitflap/core";
  import { onMount, onDestroy } from "svelte";

  // Props — same shape as SplitFlapOptions
  export let text: string;
  export let textInit: SplitFlapOptions["textInit"] = undefined;
  export let autoplay: SplitFlapOptions["autoplay"] = true;
  export let speed: SplitFlapOptions["speed"] = 3;
  export let speedVariation: SplitFlapOptions["speedVariation"] = 2;
  export let charsMap: SplitFlapOptions["charsMap"] = undefined;
  export let charWidth: SplitFlapOptions["charWidth"] = 50;
  export let charHeight: SplitFlapOptions["charHeight"] = 100;
  export let charSubstitute: SplitFlapOptions["charSubstitute"] = " ";
  export let padDir: SplitFlapOptions["padDir"] = "left";
  export let padChar: SplitFlapOptions["padChar"] = " ";
  export let stagger: SplitFlapOptions["stagger"] = 0;
  export let maxFlips: SplitFlapOptions["maxFlips"] = undefined;
  export let fontFamily: SplitFlapOptions["fontFamily"] = undefined;
  export let fontWeight: SplitFlapOptions["fontWeight"] = undefined;
  export let textColor: SplitFlapOptions["textColor"] = undefined;
  export let charBackground: SplitFlapOptions["charBackground"] = undefined;
  export let dividerColor: SplitFlapOptions["dividerColor"] = undefined;
  export let onComplete: SplitFlapOptions["onComplete"] = undefined;

  let container: HTMLDivElement;
  let instance: SplitFlapCore | null = null;

  function createInstance() {
    instance?.destroy();
    if (!container) return;
    instance = new SplitFlapCore(container, {
      text,
      textInit,
      autoplay,
      speed,
      speedVariation,
      charsMap,
      charWidth,
      charHeight,
      charSubstitute,
      padDir,
      padChar,
      stagger,
      maxFlips,
      fontFamily,
      fontWeight,
      textColor,
      charBackground,
      dividerColor,
      onComplete,
    });
  }

  onMount(createInstance);

  // Recreate when reactive props change
  $: text, textInit, autoplay, speed, speedVariation, charsMap, charWidth,
     charHeight, stagger, maxFlips, fontFamily, fontWeight, textColor,
     charBackground, dividerColor, container && createInstance();

  onDestroy(() => {
    instance?.destroy();
    instance = null;
  });
</script>

<div bind:this={container}></div>

// packages/splitflap/src/SplitFlap.tsx
import { useEffect, useRef } from "react";
import { SplitFlap as SplitFlapCore } from "@splitflap/core";
import type { SplitFlapOptions } from "@splitflap/core";

/**
 * React wrapper around @splitflap/core.
 *
 * Creates a container div, instantiates the core SplitFlap class on mount,
 * and tears it down on unmount. Reacts to prop changes by calling setText().
 */
function SplitFlap(props: SplitFlapOptions) {
  const containerRef = useRef<HTMLDivElement>(null);
  const instanceRef = useRef<SplitFlapCore | null>(null);
  // Track the initial mount text to detect prop changes
  const prevTextRef = useRef<string | null>(null);

  const {
    text,
    textInit,
    autoplay = true,
    ...rest
  } = props;

  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;

    // Destroy previous instance if any
    instanceRef.current?.destroy();

    const instance = new SplitFlapCore(el, {
      text,
      textInit,
      autoplay,
      ...rest,
    });
    instanceRef.current = instance;
    prevTextRef.current = text;

    return () => {
      instance.destroy();
      instanceRef.current = null;
    };
    // We intentionally recreate when any option changes.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [text, textInit, autoplay, rest.speed, rest.speedVariation, rest.charsMap,
      rest.charWidth, rest.charHeight, rest.charSubstitute, rest.padDir,
      rest.padChar, rest.stagger, rest.maxFlips, rest.fontFamily,
      rest.fontWeight, rest.textColor, rest.charBackground, rest.dividerColor]);

  return <div ref={containerRef} />;
}

export default SplitFlap;
